name: OPProtection
version: '2.5.3-folia'
main: org.ipsecuz.opprotection.OPProtection
api-version: '1.13'
load: POSTWORLD
author: 'Ipsecuz_, FoxStudio'
loadbefore: [PacketEvents]
softdepend: [LuckPerms]
folia-supported: true
commands:
  oppass:
    description: Quản lý xác minh OP
    usage: /<command> <password>
    permission: opprotection.oppass
    permission-message: ""
  opreload:
    description: Reload cấu hình plugin
    usage: /<command>
    permission: opprotection.opreload
    permission-message: Bạn không có quyền sử dụng lệnh này!
  verify:
    description: Yêu cầu xác minh Discord
    usage: /<command>
    permission: opprotection.verify
    permission-message: ""
  opverify:
    description: Xác minh player bằng mã xác minh (admin)
    usage: /<command> <code> [player-name]
    permission: opprotection.opverify
    permission-message: ""
permissions:
  opprotection.oppass:
    default: op
  opprotection.opreload:
    default: op
  opprotection.verify:
    default: op
  opprotection.opverify:
    default: op
  opprotection.temp:
    default: false